config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'links#new'
  resources 'links', only: %i[new create]
  get 'links/:short_link', to: 'links#show', as: 'link'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
# frozen_string_literal: true

class Link < ApplicationRecord
  before_create :random_link
  validates :short_link, uniqueness: true

  def random_link
    self.short_link = SecureRandom.hex(10) if short_link.empty?
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/links_controller.rb
# frozen_string_literal: true

class LinksController < ApplicationController
  def new
    @link = Link.new
  end

  def create
    @link = Link.new(link_params)
    if @link.save
      redirect_to link_path(@link.short_link)
    else
      render :new
    end
  end

  def show
    @link = Link.find_by(short_link: params[:short_link])
    @link.increment!(:visits)
  end

  private

  def link_params
    params.require(:link).permit(:short_link)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shorteners</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'Admin panel', rails_admin_path %>
    <br>
    <%= yield %>
  </body>
</html>

app/views/links/new.html.erb
<%= form_for @link do |f| %>
	<%= f.text_field :short_link  %>
	<%= f.submit 'Create' %>
<% end %>
<% if @link.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @link.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/links/show.html.erb
<label><%= link_url(@link.short_link) %></label>